### ISSUE TITLE
Voting system

### ISSUE THREAD

**Issue by ciarancrocker** [ciarancrocker/sgs_bot#12]
Add a feature to allow for calling a vote in a fashion similarly to below:

~call_vote @Committee Buy more bananas

This would call a vote with a topic of "Buy more bananas", and will constrain the vote to close either when all members of the role Committee have voted or after a predetermined amount of time has passed.

Calling a vote would cause the bot to create a new message with the topic of the vote and add 3 reactions, one for each of For, Against or Abstain. After closing the vote, the bot would count the number of valid votes for each category and record them in the original message. A vote would be classed as invalid if someone outside of the constrained role cast a vote or if a member has voted more than once.

**Comment by Committee** [comment]
Hello! I got tagged here? :)

**Comment by ciarancrocker** [comment]
My bad, trying to emphasise something that's common on our Discord server

**Comment by ciarancrocker** [comment]
Due to a lack of interest in this I'm closing it out. Feel free to request reopening if this is something you can contribute.
