### ISSUE TITLE
How to make yourself an admin

### ISSUE THREAD

**Issue by Valiantiam** [ciarancrocker/sgs_bot#15]
How does one go about adding yourself as an authenticated admin so that you can create new roles etc?

**Comment by ciarancrocker** [comment]
Add either the ID of a role or a user to the permissions table. The members
of the role or the specified user will be considered administrators.

**Comment by Valiantiam** [comment]
This would be a good .env variable to set at the configuration start to streamline admin access, can we have that added?

**Comment by ciarancrocker** [comment]
No; it's better suited to being in the database imo. I'll update
documentation to indicate this process soon.

**Comment by Valiantiam** [comment]
So I added myself in the permissions table but I sitll am getting denied. To clairfy this is my DB entry:

```
id  |      discord_id
----+-----------------
4   | 97049182073786368
(1 row)
```

Feel like I'm still missing something? Those values both were obtained directly from the users table.

**Comment by Valiantiam** [comment]
Nevermind. Typo on my id.

Thanks for all the help as always so far. I'm hoping to start contributing some pull requests in the near future now that I'm getting a better understanding of how this is setup.

TY.
