### ISSUE TITLE
!game_stats not handling special characters

### ISSUE THREAD

**Issue by unreturnable** [ciarancrocker/sgs_bot#19]
!game_stats doesn't seem to handle special characters like `ℍ`

The following command returns all of the game_stats data when it should default to just the first 10 rows.
```
!game_stats ℍ
```
This command with respect the limit given but will match to any game name
```
!game_stats ℍ 10
```

The full cause of this issue was not tested for but it can be assumed to lie somewhere in these lines from game_stats.js
```js
if (isNaN(args[1]) && typeof args[1] !== 'undefined') {
        data = await database.getStatisticsForGame(
          args[1].replace(/["']/g, ''),
          args[2]
        );
      } else {
        if (typeof args[1] !== 'undefined') {
          data = await database.getGameStatistics(parseInt(args[1]));
        } else {
          data = await database.getGameStatistics(10);
        }
      }
```

It would also be worth having a discussion of enforcing a 50 game stat limit in any none DM channel.

**Comment by unreturnable** [comment]
After further testing it seems to be an issue with the name look up. `ℍ` appears to match to a large number of game names in the same way a single character like `b` does. Looking at the code I can't see how this is an issue with our implementation but perhaps it's something we have to tell postgres to handle a bit better?

**Comment by ciarancrocker** [comment]
c214ae4 fixes this issue.

The command assumed that if the parameter given is not a number, as is the case for the emoji, that a second parameter for a limit is supplied. As it isn't, no limit is passed to the database. The command now assumes a default limit of 20 in the case of providing a name, or enforces a limit up to 20 if another number is provided as a limit.

**Comment by unreturnable** [comment]
The emoji still shouldn't be matching to game names though?

**Comment by ciarancrocker** [comment]
It should, but as I don't store game names in a unicode field long enough
for the H emoji to fit, it just matches everything.

**Comment by unreturnable** [comment]
Maybe characters that will be larger then the field length should return nothing or an error message?
