### ISSUE TITLE
Add more commands

### ISSUE THREAD

**Issue by dmurphy95** [ciarancrocker/sgs_bot#4]
Can you please look into adding these to the bot:

- addrank (NAME): create a new role.
- delrank (NAME): delete a rank created with addrank.
- joinrank (NAME): join a rank that was created with addrank.
- massdelete (NUMBER): delete the last n messages.
- flip: flip a coin.
- roll (NUMBER): roll an n sided die.

**Comment by ciarancrocker** [comment]
Just going to add a tick list so I can see what is and isn't done right now

- [x] ~~addrank~~ create_role
- [x] ~~delrank~~ delete_role
- [x] ~~joinrank~~ join_role
- [x] ~~massdelete~~ purge
- [x] flip
- [x] roll

**Comment by ciarancrocker** [comment]
This should be closed by commit 68f6e0.
